### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by xxxkkkmmm** [KennthShang/CHERRY#2]
Why sometimes predict the host that program does not report an error, but does not output the result?

**Comment by KennthShang** [comment]
I guess you refer to the program does not output results less than the confident THRESHOLD?

If the program thoughts there is not much confidence to make a prediction, then it will output nothing for such a phage

**Comment by xxxkkkmmm** [comment]
I have run it before without problems, but this time I don't know why, I will find the reason again, thank you!
